name: Example Release Workflow

on:
   # Monthly automatic release - patch version bump
   schedule:
      - cron: '0 0 1 * *' # Monthly on the 1st at midnight UTC

   # Manual trigger with version bump options
   workflow_dispatch:
      inputs:
         version_bump:
            description: 'Version bump type'
            required: true
            default: 'patch'
            type: choice
            options:
               - patch
               - minor
               - major

jobs:
   unit-tests:
      name: Run Unit Tests
      runs-on: ubuntu-latest
      permissions:
         contents: read
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '20'
              cache: 'npm'

         - name: Install dependencies
           run: npm ci

         - name: Run tests
           run: npm test

         - name: Check formatting
           run: npm run format-check
   create-release-pr:
      name: Create Release PR
      needs: unit-tests
      permissions:
         contents: write
         pull-requests: write
      uses: ./.github/workflows/monthly-release.yml
      with:
         version_bump: ${{ github.event_name == 'schedule' && 'patch' || github.event.inputs.version_bump }}
         trigger_type: ${{ github.event_name == 'schedule' && 'monthly' || 'manual' }}
      secrets:
         gh_token: ${{ secrets.GITHUB_TOKEN }}
